config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :teams, only: [:index, :create, :new]
  resources :weeks, only: [:index, :new, :create, :show]
  resources :rankings, only: [:index, :new, :create]
  resources :players, only: [:index, :show, :edit, :update, :create, :new]
  resources :dynasty_teams, only: [:show, :index, :trade]
  resources :trades, only: [:index, :update, :create]
  match '/customview' => 'players#customview' , via: [:get]
  match '/players/:id/edit' => 'players#update', via: [:get, :post]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  match '/trade_post' => 'dynasty_teams#trade' , via: [:update]
end

app/models/dynasty_team.rb
class DynastyTeam < ApplicationRecord
  belongs_to :owner
  has_many :player_contracts
  has_many :draft_picks
  has_many :salary_cap_adjustments

  accepts_nested_attributes_for :player_contracts
  accepts_nested_attributes_for :draft_picks

end

app/controllers/dynasty_teams_controller.rb
class DynastyTeamsController < ApplicationController

  def index
    @dynasty_teams = DynastyTeam.all
  end

  def new
    @dynasty_team = DynastyTeam.new
  end

  def create
    @dynasty_team = DynastyTeam.new(dynasty_team_params)
    if @dynasty_team.save
      redirect_to dynasty_teams_path
    else
      render :new
    end
  end

  def show
    @dynasty_team = DynastyTeam.where(id:params[:id]).first()
    @owner = Owner.where(id:@dynasty_team[:owner_id]).first()
    @player_contract = PlayerContract.where(dynasty_team_id:@dynasty_team[:id])
    @quarterbacks = Player.where(player_id:PlayerContract.where(dynasty_team_id:@dynasty_team[:id]).pluck(:player_id), position:'QB')
    @wide_receivers = Player.where(player_id:PlayerContract.where(dynasty_team_id:@dynasty_team[:id]).pluck(:player_id), position:'WR')
    @running_backs = Player.where(player_id:PlayerContract.where(dynasty_team_id:@dynasty_team[:id]).pluck(:player_id), position:'RB')
    @tight_ends = Player.where(player_id:PlayerContract.where(dynasty_team_id:@dynasty_team[:id]).pluck(:player_id), position:'TE' )
    @kickers = Player.where(player_id:PlayerContract.where(dynasty_team_id:@dynasty_team[:id]).pluck(:player_id), position:'K')
    @defenses = Player.where(player_id:PlayerContract.where(dynasty_team_id:@dynasty_team[:id]).pluck(:player_id), position:'DEF')
    @players = Player.where(player_id:PlayerContract.where(dynasty_team_id:@dynasty_team[:id]).pluck(:player_id))
    @draft_picks = DraftPick.where(dynasty_team_id:@dynasty_team[:id])
    @current_year = Date.today.year
    # if Date.today < Date.new(@current_year,09,01)
    #   @
    # else

    #end
    @next_year = @current_year + 1
    @two_years_from_now = @next_year + 1
    @draft_picks_this_year = DraftPick.where(dynasty_team_id:@dynasty_team[:id], year:@current_year)
    @draft_picks_next_year = DraftPick.where(dynasty_team_id:@dynasty_team[:id], year:@next_year)
    @draft_picks_two_years_from_now = DraftPick.where(dynasty_team_id:@dynasty_team[:id], year:@two_years_from_now)
    @salary_cap_adjustments = SalaryCapAdjustment.where(cap_sender_id: @dynasty_team[:id]).or(SalaryCapAdjustment.where(cap_recipient_id: @dynasty_team[:id]))
    @net_adjustment = 0
    @salary_cap_adjustments.each do |adjustment|
      if adjustment.cap_sender_id == @dynasty_team.id
        @net_adjustment -= adjustment.cap_adjustment
      else
        @net_adjustment += adjustment.cap_adjustment
      end
    end
    @salary_cap = 300
    @total_player_cost = 0
    @player_contract.each do |contract|
      if contract.current_salary < 15
        @total_player_cost += (contract.current_salary + 1)
        puts Player.where(player_id:contract.player_id).first()[:name] +":" + (contract.current_salary + 1).to_s
      else
        @total_player_cost += (contract.current_salary*1.1).round
        puts Player.where(player_id:contract.player_id).first()[:name] + ":" + (contract.current_salary*1.1).round.to_s
      end
    end
  end

  def player_params
    params.require(:player).permit(
        :player_id, :esbid, :gsisPlayerId, :name, :position, :teamAbbr, :stats_id
    )
  end

end

app/views/dynasty_teams/index.html.erb
<% @dynasty_teams.each do |team| %>
    <div id=team.id align="center"><%= link_to(team.team_name, dynasty_team_path(team.id))%></div><br>
<% end %>

app/views/dynasty_teams/show.html.erb
<style>
  .col-1{float:left; width:16.6%;}
  .col-2{float:left; width:16.6%;}
  .col-3{float:left; width:16.6%;}
  .col-4{float:left; width:16.6%;}
  .col-5{float:left; width:16.6%;}
  .col-6{float:left; width:16.6%;}
    h1{font-size:25px}
    h2{font-size:20px}
    h3{font-size:10px}
    p{font-size:10px}
  .playerbox{border:outset}
</style>
<div id="TEAM_NAME" align="center"><h1><%= @dynasty_team.team_name %></h1></div>
<div id="OWNER_NAME" align="center"><h2><%= @owner.first_name %> <%=@owner.last_name %></h2></div>
<div class="col-1" width=16.66% class="float-left">
  <h3 align="center">QUARTERBACKS (<%= @quarterbacks.count() %>)</h3>
  <% @quarterbacks.each do |qb| %>
      <div class="playerbox">
        <% if qb['esbid'] != nil %>
            <%= image_tag('http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/'+qb['esbid']+'.png', size: "35x35") %><br>
        <% end %>
        <p><%= qb.name %>,
        <%= qb.position %><br>
        <%= qb.teamAbbr %><br>
        <%= link_to('NFL PROFILE PAGE', 'http://www.nfl.com/player/'+qb['name'].delete(' ')+'/'+qb['player_id'].to_s+'/profile') %>
         - <%= link_to('WDD PAGE', player_path(qb.id)) %><br>
        Current Salary: $<%= @player_contract.where(player_id: qb[:player_id]).first().current_salary %>
        <% if @player_contract.where(player_id: qb[:player_id]).first().current_salary < 15 %>
              -- Next Year Proj: $<%= @player_contract.where(player_id: qb[:player_id]).first().current_salary + 1 %>
        <% else %>
              -- Next Year Proj: $<%= (@player_contract.where(player_id: qb[:player_id]).first().current_salary * 1.1).round %>
        <% end %>
        <% if @player_contract.where(player_id: qb[:player_id]).first().is_top_fourteen %>
            <br>Top 14 Player
        <% end %>
        <br>First Year Under Contract: <%= @player_contract.where(player_id: qb[:player_id]).first().first_year %>
        </p>
      </div>
  <% end %>
</div>

<div class="col-2" width=16.66% class="float-left">
  <h3 align="center">RUNNINGBACKS (<%= @running_backs.count() %>)</h3>
    <% @running_backs.each do |rb| %>
      <div class="playerbox">
        <% if rb['esbid'] != nil %>
            <%= image_tag('http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/'+rb['esbid']+'.png', size: "35x35") %><br>
        <% end %>
        <p>
        <%= rb.name %>,
        <%= rb.position %><br>
        <%= rb.teamAbbr %><br>
        <%= link_to('NFL PROFILE PAGE', 'http://www.nfl.com/player/'+rb['name'].delete(' ')+'/'+rb['player_id'].to_s+'/profile') %><br>
        Current Salary: $<%= @player_contract.where(player_id: rb[:player_id]).first().current_salary %>
          <% if @player_contract.where(player_id: rb[:player_id]).first().current_salary < 15 %>
              -- Next Year Proj: $<%= @player_contract.where(player_id: rb[:player_id]).first().current_salary + 1 %>
          <% else %>
              -- Next Year Proj: $<%= (@player_contract.where(player_id: rb[:player_id]).first().current_salary * 1.1).round %>
          <% end %>
        <% if @player_contract.where(player_id: rb[:player_id]).first().is_top_fourteen %>
            <br>Top 14 Player
        <% end %>
        <br>First Year Under Contract: <%= @player_contract.where(player_id: rb[:player_id]).first().first_year %>
        </p>
      </div>
    <% end %>
</div>

<div class="col-3" width=16.66% class="float-left">
  <h3 align="center">WIDE RECEIVERS (<%= @wide_receivers.count() %>)</h3>
    <% @wide_receivers.each do |wr| %>
      <div class="playerbox">
        <% if wr['esbid'] != nil %>
            <%= image_tag('http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/'+wr['esbid']+'.png', size: "35x35") %><br>
        <% end %>
        <p><%= wr.name %>,
        <%= wr.position %><br>
        <%= wr.teamAbbr %><br>
        <%= link_to('NFL PROFILE PAGE', 'http://www.nfl.com/player/'+wr['name'].delete(' ')+'/'+wr['player_id'].to_s+'/profile') %><br>
        Current Salary: $<%= @player_contract.where(player_id: wr[:player_id]).first().current_salary %>
        <% if @player_contract.where(player_id: wr[:player_id]).first().current_salary < 15 %>
              -- Next Year Proj: $<%= @player_contract.where(player_id: wr[:player_id]).first().current_salary + 1 %>
        <% else %>
              -- Next Year Proj: $<%= (@player_contract.where(player_id: wr[:player_id]).first().current_salary * 1.1).round %>
        <% end %>
          <% if @player_contract.where(player_id: wr[:player_id]).first().is_top_fourteen %>
            <br>Top 14 Player
        <% end %>
        <br>First Year Under Contract: <%= @player_contract.where(player_id: wr[:player_id]).first().first_year %>
        </p>
      </div>
    <% end %>
</div>

<div class="col-4" width=16.66% class="float-left">
  <h3 align="center">TIGHT ENDS (<%= @tight_ends.count() %>)</h3>
    <% @tight_ends.each do |te| %>
      <div class="playerbox">
        <% if te['esbid'] != nil %>
            <%= image_tag('http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/'+te['esbid']+'.png', size: "35x35") %><br>
        <% end %>
        <p><%= te.name %>,
        <%= te.position %><br>
        <%= te.teamAbbr %><br>
        <%= link_to('NFL PROFILE PAGE', 'http://www.nfl.com/player/'+te['name'].delete(' ')+'/'+te['player_id'].to_s+'/profile') %><br>
        Current Salary: $<%= @player_contract.where(player_id: te[:player_id]).first().current_salary %>
        <% if @player_contract.where(player_id: te[:player_id]).first().current_salary < 15 %>
              -- Next Year Proj: $<%= @player_contract.where(player_id: te[:player_id]).first().current_salary + 1 %>
        <% else %>
              -- Next Year Proj: $<%= (@player_contract.where(player_id: te[:player_id]).first().current_salary * 1.1).round %>
        <% end %>
        <% if @player_contract.where(player_id: te[:player_id]).first().is_top_fourteen %>
            <br>Top 14 Player
        <% end %>
        <br>First Year Under Contract: <%= @player_contract.where(player_id: te[:player_id]).first().first_year %>
        </p>
      </div>
    <% end %>
</div>

<div class="col-5" width=16.66% class="float-left">
  <h3 align="center">K (<%= @kickers.count() %>) DEFENSES (<%= @defenses.count() %>)</h3>
    <% @kickers.each do |k| %>
      <div class="playerbox">
        <% if k['esbid'] != nil %>
            <%= image_tag('http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/'+k['esbid']+'.png', size: "35x35") %><br>
        <% end %>
        <p><%= k.name %>,
        <%= k.position %><br>
        <%= k.teamAbbr %><br>
        <%= link_to('NFL PROFILE PAGE', 'http://www.nfl.com/player/'+k['name'].delete(' ')+'/'+k['player_id'].to_s+'/profile') %><br>
        Current Salary: $<%= @player_contract.where(player_id: k[:player_id]).first().current_salary %>
        <% if @player_contract.where(player_id: k[:player_id]).first().current_salary < 15 %>
              -- Next Year Proj: $<%= @player_contract.where(player_id: k[:player_id]).first().current_salary + 1 %>
        <% else %>
              -- Next Year Proj: $<%= (@player_contract.where(player_id: k[:player_id]).first().current_salary * 1.1).round %>
        <% end %>
        <% if @player_contract.where(player_id: k[:player_id]).first().is_top_fourteen %>
          <br>Top 14 Player
        <% end %>
        <br>First Year Under Contract: <%= @player_contract.where(player_id: k[:player_id]).first().first_year %>
        </p>
      </div>
    <% end %>
    <% @defenses.each do |defense| %>
      <div class="playerbox">
        <% if defense['esbid'] != nil %>
            <%= image_tag('http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/'+defense['esbid']+'.png', size: "35x35") %><br>
        <% end %>
        <p><%= defense.name %>,
          <%= defense.position %><br>
          <%= defense.teamAbbr %><br>
          Current Salary: $<%= @player_contract.where(player_id: defense[:player_id]).first().current_salary %>
          <% if @player_contract.where(player_id: defense[:player_id]).first().current_salary < 15 %>
              -- Next Year Proj: $<%= @player_contract.where(player_id: defense[:player_id]).first().current_salary + 1 %>
          <% else %>
              -- Next Year Proj: $<%= (@player_contract.where(player_id: rb[:player_id]).first().current_salary * 1.1).round %>
          <% end %>
          <% if @player_contract.where(player_id: defense[:player_id]).first().is_top_fourteen %>
              <br>Top 14 Player
          <% end %>
          <br>First Year Under Contract: <%= @player_contract.where(player_id: defense[:player_id]).first().first_year %>
        </p>
      </div>
  <% end %>
</div>

<div class="col-6" width=16.66% class="float-left">
  <h3 align="center"><%= @current_year %> Draft Picks</h3>
  <% @draft_picks_this_year.each do |pick| %>
      <div class="playerbox">
        <div align="center">
          Round: <%= pick.round %>
          <% if pick.pick != nil %>
              - Pick: <%= pick.pick %><br>
          <% elsif pick.comments != 'None'  %>
              - <%= pick.comments %>
          <% end %>
        </div>
      </div>
  <% end %>
  <h3 align="center"><%= @next_year %> Draft Picks</h3>
  <% @draft_picks_next_year.each do |pick| %>
      <div class="playerbox">
        <div align="center">
        Round: <%= pick.round %>
        <% if pick.pick != nil %>
            - Pick: <%= pick.pick %><br>
        <% elsif pick.comments != 'None'  %>
            - <%= pick.comments %>
        <% end %>
        </div>
      </div>
  <% end %>
  <h3 align="center"><%= @two_years_from_now %> Draft Picks</h3>
  <% @draft_picks_two_years_from_now.each do |pick| %>
      <div class="playerbox">
        <div align="center">
          Round: <%= pick.round %>
          <% if pick.pick != nil %>
              - Pick: <%= pick.pick %><br>
          <% elsif pick.comments != 'None'  %>
              - <%= pick.comments %>
          <% end %>
        </div>
      </div>
  <% end %>
  <h3 align="center">Salary Cap -<%=  @current_year %></h3>
  <div class="playerbox">
    <div align="center">Cost of Players: $<%= @total_player_cost %></div>
  </div>
  <div class="playerbox">
    <div align="center">Net Adjustment: $<%= @net_adjustment %></div>
  </div>
  <div class="playerbox">
    <div align="center">Current Cap: $<%= @total_player_cost-@net_adjustment %></div>
  </div>
  <div class="playerbox">
    <div align="center">Net Cap Space: <%= 300-(@total_player_cost-@net_adjustment) %></div>
  </div>
  <h3 align="center"> Cap Transactions </h3>
  <% @salary_cap_adjustments.each do |cap_adjustment| %>
    <div class="playerbox">
      <div align="center">
      <% if cap_adjustment.cap_sender_id == @dynasty_team.id %>
          <%= cap_adjustment.comments %><br>
      <% else %>
          <%= cap_adjustment.comments %><br>
      <% end %>
      </div>
    </div>
  <% end %>
</div>