config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :teams, only: [:index, :create, :new]
  resources :weeks, only: [:index, :new, :create, :show]
  resources :rankings, only: [:index, :new, :create]
  resources :players, only: [:index, :show, :edit, :update, :create, :new]
  resources :dynasty_teams, only: [:show, :index, :trade]
  resources :trades, only: [:index, :update, :create]
  match '/customview' => 'players#customview' , via: [:get]
  match '/players/:id/edit' => 'players#update', via: [:get, :post]
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  match '/trade_post' => 'dynasty_teams#trade' , via: [:update]
end

app/models/player.rb
class Player < ApplicationRecord
  # has_one :dynasty_team, primary_key: 'player_id', foreign_key: 'player_id'
  has_one :player_contract, primary_key: 'player_id', foreign_key: 'player_id'
  searchkick

  validates_uniqueness_of :player_id, presence: true

  def self.get_players_from_name_list(list)
    Player.connection.execute('select name, player_id from players where name in ('+list+')')
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    # @players = HTTParty.get("http://api.fantasy.nfl.com/v1/players/stats?statType=seasonStats&format=json")
    # @dumpPlayerData = player_data_dump
    #@players = Player.all
    if params[:query].present?
      @players = Player.search(params[:query], page: params[:page])
    else
      @players = Player.all.page params[:page]
    end
  end

  def customview
    @count = 1
    @draft_picks = [
    'DAN',
    'ALEX',
    'GOAT',
    'ROB',
    'JONO',
    'ADAM',
    'NATE',
    'BILLY',
    'PEALER',
    'BRENDAN',
    'JUSTIN',
    'BARD',
    'FISCHETTI',
    'DEREK'
    ]
  end

  def new
    respond_to do |format|

      @player = Player.new

      format.html
      format.json { render json: @player }

    end
  end

  def edit
    @player = Player.find_by(id:params[:id])
    @player_contract = PlayerContract.find_by(player_id:@player[:player_id])
    if @player_contract != nil
      @contract_type = ContractType.find_by(id:@player_contract.contract_type_id)
      @team = DynastyTeam.find_by(id:@player_contract.dynasty_team_id)
    end
  end

  def create
    if params['player']['name'] == nil
      @player_id = params[:player][:id]
    else
      new_player = Player.new(
        player_id: params['player']['player_id'].to_i,
        esbid: params['player']['esbid'],
        gsisPlayerId: params['player']['gsisPlayerId'],
        name: params['player']['name'],
        position: params['player']['position'],
        teamAbbr: params['player']['teamAbbr']
      )
      if new_player.save
        flash[:notice] = 'Player has been successfully added'
        redirect_to new_player_path
      else
        flash[:success] = 'Try again.'
        redirect_to new_player_path
      end
    end
    if params["commit"] != 'Add Player'
      @player_json = HTTParty.get("http://api.fantasy.nfl.com/v1/players/details?playerId="+@player_id)
      @player_json = @player_json["players"][0]
      respond_to do |format|
        format.js { render 'players/show_update'}
      end
    end
  end

  def show
    @player = Player.find_by(id:params[:id])
    @player_contract = PlayerContract.find_by(player_id:@player[:player_id])
    if @player_contract != nil
      @contract_type = ContractType.find_by(id:@player_contract.contract_type_id)
      @team = DynastyTeam.find_by(id:@player_contract.dynasty_team_id)
    end
  end

  def update
    player_contract = PlayerContract.find_by(player_id:player_contract_params[:player_id])
    if player_contract == nil
      @player_contract = PlayerContract.new(player_contract_params)
      if @player_contract.save
        redirect_to player_path
      else
        flash["Did not save"]
      end
    else
      PlayerContract.update(player_contract.id, player_contract_params)
      redirect_to player_path
    end
  end

  def player_data_dump
    dump = DumpDataService.new

    dump.dump_players
  end

  def autocomplete
    #render json: Player.search(params[:query], autocomplete: true, limit: 10).map(&:name)
  end

  def player_params
    params.require(:player).permit(
      :player_id, :esbid, :gsisPlayerId, :name, :position, :teamAbbr, :stats_id, :id
    )
  end
  def player_contract_params
    params.require(:player_contract).permit(
        :player_id, :dynasty_team_id, :contract_type_id, :first_year, :is_top_fourteen, :current_salary
    )
  end

end

app/views/players/_form.html.erb
<%= form_for Player.new do |f| %>
    <%= image_tag('http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/'+@player_json['esbid']+'.png') %><br>
    Player ID: <%= f.text_field :player_id, value: @player_json['id']  %>
    esbid: <%= f.text_field :esbid, value: @player_json['esbid']  %>
    gsisPlayerId: <%= f.text_field :gsisPlayerId, value: @player_json['gsisPlayerId']  %>
    Name: <%= f.text_field :name, value: @player_json['name']  %>
    position: <%= f.text_field :position, value: @player_json['position']  %>
    teamAbbr: <%= f.text_field :teamAbbr, value: @player_json['teamAbbr']  %>

    <%= f.submit 'Add Player' %>
<% end %><br>

app/views/players/customview.html.erb
customview page

<% @draft_picks.each do |draft_pick| %>
    <%= "DraftPick.create(dynasty_team_id:DynastyTeam.where(team_name:"+draft_pick.to_s+").first().id," %><br>
    <%="year:2019,"%><br>
    <%="round:1,"%><br>
    <%="comments:'None')" %><br>
    <br><br>
    <%	 @count += 1 %>
<% end %>

<% @draft_picks.each do |draft_pick| %>
    <%= "DraftPick.create(dynasty_team_id:DynastyTeam.where(team_name:"+draft_pick.to_s+").first().id," %><br>
    <%="year:2019,"%><br>
    <%="round:2,"%><br>
    <%="comments:'None')" %><br>
    <br><br>
    <%	 @count += 1 %>
<% end %>

<% @draft_picks.each do |draft_pick| %>
    <%= "DraftPick.create(dynasty_team_id:DynastyTeam.where(team_name:"+draft_pick.to_s+").first().id," %><br>
    <%="year:2019,"%><br>
    <%="round:3,"%><br>
    <%="comments:'None')" %><br>
    <br><br>
    <%	 @count += 1 %>
<% end %>

app/views/players/edit.html.erb
Name: <%= @player.name %><br />
Position: <%= @player.position %><br />
NFL Team: <%= @player.teamAbbr %><br />
NFL Player ID: <%= @player.player_id %><br />
NFL ESBID: <%= @player.esbid %><br />
NFL GSIS Player ID: <%= @player.gsisPlayerId %><br />


<%= form_for :player_contract do |f| %>
    Dynasty Team ID : <%= f.collection_select :dynasty_team_id, DynastyTeam.order(:team_name),:id, :team_name, include_blank: true %><br />
    Contract Type : <%= f.collection_select :contract_type_id, ContractType.all, :id, :name, include_blank: true %><br />
    First Year of Contract : <%= f.select :first_year, (Time.zone.now.year - 10)..(Time.zone.now.year + 2) %><br />
    <%= f.text_field :current_salary  %><br />
    Top Fourteen?    : <%= f.check_box :is_top_fourteen %><br />
    <%= f.hidden_field :player_id, :value => @player.player_id%>
    <%= f.submit %>
<% end %>

app/views/players/index.html.erb
<%= form_tag players_path, class: "form-inline", method: :get do %>
    <%= text_field_tag :query, params[:query], class: "form-control" %>
<% end %>

<%= submit_tag "Search", class: "btn btn-primary" %>
<% if params[:query].present? %>
    <%= link_to "clear", players_path %>
<% end %>
<div class="centeredHomePage">
  <% @players.first(10).each do |player| %>
    <%=  player.name %><br>
      <% if player.esbid != nil && player.name != nil %>
          <%= image_tag('http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/'+player.esbid+'.png') %><br>
          External Player Page: <%= link_to('NFL Profile Page', 'http://www.nfl.com/player/'+player.name.delete(' ')+'/'+player.player_id.to_s+'/profile') %><br>
          WDD Player Page: <%= link_to(player.name, player_path(player.id))%><br><br>
      <% end %>
      <br>
  <% end %>
</div>

app/views/players/new.html.erb
<script type="text/javascript">
//  document.getElementById('btn').onclick = function() {
//    var val = document.getElementById('imagename').value,
//        src = 'http://webpage.com/images/' + val +'.png',
//        img = document.createElement('img');
//
//    img.src = src;
//    document.body.appendChild(img);
//  }
</script>

<%= form_for(@player, remote: true)  do |f| %>
    <%= f.text_field :id, autofocus: true, class: 'title-field pull-left' %>
    <%= f.submit 'Generate Player Information', class: 'btn home-add without-entry' %>
<% end %>

<div id="your_form_id" class="your_form_id">
  <!-- form div -->
</div>

app/views/players/show.html.erb
<%= @player.name %><br>
<% if @player.esbid != nil %>
  <%= image_tag('http://static.nfl.com/static/content/public/static/img/fantasy/transparent/200x200/'+@player.esbid+'.png') %><br>
<%	 end %>
<%= @player.position %><br>
<%= @player.teamAbbr %><br>
<br>
<br>
<% if @team != nil %>
  SALARY: <%= @player_contract.current_salary %><br>
  First Year Under Contract: <%= @player_contract.first_year %><br>
  Type of Contract: <%= @contract_type.name %><br>
  WDD Team: <%= link_to(@team.team_name, dynasty_team_path(@team.id)) %><br>
  <% if @player_contract.is_top_fourteen %>
      <p>This Player has been Top 14 at his position</p><br>
  <% end %>
<% end %>

app/views/players/show_update.js.erb
$("#your_form_id").html("<%=j render 'form' %>");